package training.admin.system.controller.menu;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.security.Provider.Service;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletResponse;

import org.apache.tomcat.util.http.fileupload.IOUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import jxl.Workbook;
import jxl.format.Alignment;
import jxl.format.BoldStyle;
import jxl.format.Border;
import jxl.format.BorderLineStyle;
import jxl.format.Colour;
import jxl.write.Label;
import jxl.write.WritableCell;
import jxl.write.WritableCellFormat;
import jxl.write.WritableFont;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;
import training.admin.system.AchievementData;
import training.admin.system.model.Achievement;
import training.admin.system.model.User;
import training.admin.system.repository.AchievementRepository;
import training.admin.system.repository.OfficeRepository;
import training.admin.system.repository.UserRepository;

@RestController
@RequestMapping("/achievement")
public class AchievementController {
	
	@Autowired
	AchievementRepository achievementRepository;
	@Autowired
	UserRepository userRepository;
	@Autowired
	OfficeRepository officeRepository;
	
	@RequestMapping(value="/all", method=RequestMethod.GET)
	public List<Achievement> findAll( ) {
		return achievementRepository.findAll();
	}
	
	@RequestMapping(value="/allPage", method=RequestMethod.GET)
	public Page<Achievement> findAll(Pageable pageable) {
		return achievementRepository.findAll(pageable);
	}
	
	@GetMapping (value="/findAllUser")
	public List<AchievementData> findAllUser(){
		List <AchievementData> listAchievment = new ArrayList<AchievementData>();
		List <User> users = userRepository.findAll();
		for (User user:users) {
			listAchievment.add(convertAchievementToAchievementData(user));
		}
		return listAchievment;
	}
	
	@GetMapping(value="/findByUser/{idUser}")
	public AchievementData findByUser(@PathVariable Long idUser){
		User user = userRepository.findOne(idUser);
		return convertAchievementToAchievementData(user);
	}
	
	@GetMapping (value="/download")
	@ResponseBody
	public Boolean exportToExcel(HttpServletResponse response) { 
		try {
			File newFile = new File("Achievement.xls");
			WritableWorkbook workbook = Workbook.createWorkbook(newFile);
            WritableSheet sheet = workbook.createSheet("Achievement", 0);
            
           	List <String> header = new ArrayList<String>();
           	header.add("Employee ID");
           	header.add("Employee Name");
           	header.add("Job Family");
           	header.add("Grade");
           	header.add("Office");
           	header.add("Beginning");
           	header.add("LI 1");
           	header.add("LI 2");
           	header.add("Int. 1");
           	header.add("Int. 2");
           	header.add("BW 1");
           	header.add("CE 1");
           	header.add("BW 2");
           	header.add("CE 2");
           	header.add("Presentatio Skills 2");
           	
        	//------------ Format font for info -------------------
           	WritableCellFormat cellInfoFormat = new WritableCellFormat();
           	WritableFont infoFont = new WritableFont(WritableFont.ARIAL, 8);
           	cellInfoFormat.setFont(infoFont);

           	sheet.mergeCells(1, 0, 15, 0);
           	Date now = new Date(System.currentTimeMillis());
           	String info = "Generated by system at " + now;
           	System.out.println(info);
           	Label infolabel = new Label (1, 0, info, cellInfoFormat);
           	sheet.addCell(infolabel);
           	

           	//------------ Format font for title -------------------
           	WritableCellFormat cellTitleFormat = new WritableCellFormat();
           	WritableFont titleFont = new WritableFont(WritableFont.ARIAL, 16);
           	cellTitleFormat.setFont(titleFont);
           	cellTitleFormat.setAlignment(Alignment.CENTRE);
           	
        	sheet.mergeCells(1, 2, 15, 2);
           	Label title = new Label (1, 2, "List of Achievement - Training Admin System", cellTitleFormat);
           	sheet.addCell(title);

         
           	//------------ Format font for header--------------------
           	Colour bckcolor = (Colour) Colour.AQUA;
       		WritableCellFormat cellFormatHeader = new WritableCellFormat();
            cellFormatHeader.setBackground(bckcolor);
           	
            WritableFont font = new WritableFont(WritableFont.ARIAL);
            font.setBoldStyle(WritableFont.BOLD);
            cellFormatHeader.setFont(font);
            cellFormatHeader.setBorder(Border.ALL, BorderLineStyle.THIN);
            
           	for (int i = 1; i <= header.size(); i++) {
                Label headerLabel = new Label(i, 4, header.get(i-1), cellFormatHeader);
                sheet.addCell(headerLabel);
            }
           	
           	List <AchievementData> listAchievment = new ArrayList<AchievementData>();
    		List <User> users = userRepository.findAll();
    		for (User user:users) {
    			listAchievment.add(convertAchievementToAchievementData(user));
    		}
           	
    		
    		//-------------- Format font for content -----------------------
    		WritableCellFormat cellFormatBody = new WritableCellFormat();
    		cellFormatBody.setBorder(Border.ALL, BorderLineStyle.THIN);
    		Integer row=5;
    		for (AchievementData achievementData:listAchievment) {
                sheet.addCell(new Label(1, row, achievementData.getIdEmployee().toString()));
                sheet.getWritableCell(1, row).setCellFormat(cellFormatBody);
                sheet.addCell(new Label(2, row, achievementData.getEmployeeName()));
                sheet.getWritableCell(2, row).setCellFormat(cellFormatBody);
                sheet.addCell(new Label(3, row, achievementData.getJobFamily()));
                sheet.getWritableCell(3, row).setCellFormat(cellFormatBody);
                sheet.addCell(new Label(4, row, achievementData.getGrade()));
                sheet.getWritableCell(4, row).setCellFormat(cellFormatBody);
                sheet.addCell(new Label(5, row, achievementData.getOffice()));
                sheet.getWritableCell(5, row).setCellFormat(cellFormatBody);
                sheet.addCell(new Label(6, row, achievementData.getBeginning()));
                sheet.getWritableCell(6, row).setCellFormat(cellFormatBody);
                sheet.addCell(new Label(7, row, achievementData.getLI1()));
                sheet.getWritableCell(7, row).setCellFormat(cellFormatBody);
                sheet.addCell(new Label(8, row, achievementData.getLI2()));
                sheet.getWritableCell(8, row).setCellFormat(cellFormatBody);
                sheet.addCell(new Label(9, row, achievementData.getInt1()));
                sheet.getWritableCell(9, row).setCellFormat(cellFormatBody);
                sheet.addCell(new Label(10, row, achievementData.getInt2()));
                sheet.getWritableCell(10, row).setCellFormat(cellFormatBody);
                sheet.addCell(new Label(11, row, achievementData.getBW1()));
                sheet.getWritableCell(11, row).setCellFormat(cellFormatBody);
                sheet.addCell(new Label(12, row, achievementData.getCE1()));
                sheet.getWritableCell(12, row).setCellFormat(cellFormatBody);
                sheet.addCell(new Label(13, row, achievementData.getBW2()));
                sheet.getWritableCell(13, row).setCellFormat(cellFormatBody);
                sheet.addCell(new Label(14, row, achievementData.getCE2()));
                sheet.getWritableCell(14, row).setCellFormat(cellFormatBody);
                sheet.addCell(new Label(15, row, achievementData.getPresentationSkill2()));
                sheet.getWritableCell(15, row).setCellFormat(cellFormatBody);
                row++;
    		}
           	
           	workbook.write();
            workbook.close();
            

           	response.setHeader("Content-disposition","attachment; filename=" + "Achievement.xls");
            FileInputStream in = new FileInputStream(newFile);
            IOUtils.copy(in, response.getOutputStream());
            response.flushBuffer();
            return true;
		} catch (IOException | WriteException e) {
			System.out.println(e);
		    return false;
		}
		
	}
	
	public AchievementData convertAchievementToAchievementData(User user){
		AchievementData achievementData = new AchievementData();
		achievementData.setIdEmployee(user.getIdUser());
		achievementData.setEmployeeName(user.getName());
		achievementData.setJobFamily(user.getJobFamilyStream());
		achievementData.setGrade(user.getGrade());
		achievementData.setOffice(officeRepository.getOne(user.getIdOffice()).getCity());
		
		String beginning = "-";
		String LI1 = "-";
		String LI2 = "-";
		String Int1 = "-";
		String Int2 = "-";
		String BW1 = "-";
		String BW2 = "-";
		String CE1 = "-";
		String CE2 = "-";
		String PresentationSkill = "-";
		
		String beginningStatus = "";
		String LI1Status = "-";
		String LI2Status = "-";
		String Int1Status = "-";
		String Int2Status = "-";
		String BW1Status = "-";
		String BW2Status = "-";
		String CE1Status = "-";
		String CE2Status = "-";
		String PresentationSkillStatus = "-";
		
		List<Achievement> userAchievement = achievementRepository.findByUser(user);
		for (Achievement achievement:userAchievement) {
						
			switch (achievement.getCourse().getName()) {
			case "Beginning":
				beginningStatus = achievement.getStatus();
				beginning = achievement.getStatus().compareTo("Term")==0 ? achievement.getTraining().getTrainingName() : achievement.getStatus();
				break;
			case "Low Intermediete 1":
				LI1Status = achievement.getStatus();
				LI1 = achievement.getStatus().compareTo("Term")==0 ? achievement.getTraining().getTrainingName() : achievement.getStatus();
				break;
			case "Low Intermediete 2":
				LI2Status = achievement.getStatus();
				LI2 = achievement.getStatus().compareTo("Term")==0 ? achievement.getTraining().getTrainingName() : achievement.getStatus();
				break;
			case "Intermediete 1":
				Int1Status = achievement.getStatus();
				Int1 = achievement.getStatus().compareTo("Term")==0 ? achievement.getTraining().getTrainingName() : achievement.getStatus();
				break;
			case "Intermediete 2":
				Int2Status = achievement.getStatus();
				Int2 = achievement.getStatus().compareTo("Term")==0 ? achievement.getTraining().getTrainingName() : achievement.getStatus();
				break;
			case "Business Writing 1":
				BW1Status = achievement.getStatus();
				BW1 = achievement.getStatus().compareTo("Term")==0 ? achievement.getTraining().getTrainingName() : achievement.getStatus();
				break;
			case "Business Writing 2":
				BW2Status = achievement.getStatus();
				BW2 = achievement.getStatus().compareTo("Term")==0 ? achievement.getTraining().getTrainingName() : achievement.getStatus();
				break;
			case "Communicating Effectively 1":
				CE1Status = achievement.getStatus();
				CE1 = achievement.getStatus().compareTo("Term")==0 ? achievement.getTraining().getTrainingName() : achievement.getStatus();
				break;
			case "Communicating Effectively 2":
				CE2Status = achievement.getStatus();
				CE2 = achievement.getStatus().compareTo("Term")==0 ? achievement.getTraining().getTrainingName() : achievement.getStatus();
				break;
			case "Presentation Skills 2":
				PresentationSkillStatus = achievement.getStatus();
				PresentationSkill = achievement.getStatus().compareTo("Term")==0 ? achievement.getTraining().getTrainingName() : achievement.getStatus();
			default:
				break;
			}
		}
		
		achievementData.setBeginning(beginning);
		achievementData.setLI1(LI1);
		achievementData.setLI2(LI2);
		achievementData.setInt1(Int1);
		achievementData.setInt2(Int2);
		achievementData.setBW1(BW1);
		achievementData.setCE1(CE1);
		achievementData.setBW2(BW2);
		achievementData.setCE2(CE2);
		achievementData.setPresentationSkill2(PresentationSkill);
		achievementData.setBeginningStatus(beginningStatus);
		achievementData.setLI1Status(LI1Status);
		achievementData.setLI2Status(LI2Status);
		achievementData.setInt1Status(Int1Status);
		achievementData.setInt2Status(Int2Status);
		achievementData.setBW1Status(BW1Status);
		achievementData.setCE1Status(CE1Status);
		achievementData.setBW2Status(BW2Status);
		achievementData.setCE2Status(CE2Status);
		achievementData.setPresentationSkill2Status(PresentationSkillStatus);
		return achievementData;
	}
}
