export class SchedulePeriod { 
    constructor ( 
       public idSchedule: string,  
       public name: string,
       public mainTrainer: string,
       public backupTrainer: string,
       public room: string,
       public day: string,
       public hour: string,
       public startTime: string,
       public endTime: string,
       public capacity: string,
       public participantNumber: string,
       public scheduleType: string,
       public periodic: boolean,
       public createdBy: string,
       public createdAt: string,
       public updatedBy: string,
       public updatedAt: string,
       public city: string,
       public _startDate: Date,
       public _endDate: Date,
       public _Course: number,
       public _Room: number,
       public _Training: number,
       public _MainTrainer: number,
       public _BackupTrainer: number,
    ) {  } 
 }